// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBur3CCtukgVwcR6BE2L_cGyuUxFQgabwo',
    appId: '1:833054478570:web:05a7c55a4adc4b0d814793',
    messagingSenderId: '833054478570',
    projectId: 'portifolio-claes-erik',
    authDomain: 'portifolio-claes-erik.firebaseapp.com',
    storageBucket: 'portifolio-claes-erik.firebasestorage.app',
    measurementId: 'G-ND3LRSF6J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeT_LAwy5Y5tbRVZaf7Y1rQWznqz4q49E',
    appId: '1:833054478570:android:a7e6c89d655d238f814793',
    messagingSenderId: '833054478570',
    projectId: 'portifolio-claes-erik',
    storageBucket: 'portifolio-claes-erik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCopBnbpuLat2TQbV-nS8vW1xIOfrVYeSQ',
    appId: '1:833054478570:ios:c888aa07d2e6f72e814793',
    messagingSenderId: '833054478570',
    projectId: 'portifolio-claes-erik',
    storageBucket: 'portifolio-claes-erik.firebasestorage.app',
    iosBundleId: 'com.portifolioclaeserik.claesErik',
  );
}
